@PracticalAPI_HostAddress =  https://localhost:63839

GET {{PracticalAPI_HostAddress}}/Samples/Greeting
Accept: application/json

###

GET {{PracticalAPI_HostAddress}}/Samples/Greeting2
Accept: application/json

###


GET {{PracticalAPI_HostAddress}}/Samples/ExceptionTest
Accept: application/json

###


GET {{PracticalAPI_HostAddress}}/Samples/BadRequest
Accept: application/json

###
